CREATE TABLE matches (
    match_id VARCHAR(100) PRIMARY KEY,
    gameweek INTEGER NOT NULL,
    kickoff_time TIMESTAMP NOT NULL,
    home_team INTEGER NOT NULL,
    home_team_elo DECIMAL(10,2),
    home_score INTEGER NOT NULL,
    away_score INTEGER NOT NULL,
    away_team INTEGER NOT NULL,
    away_team_elo DECIMAL(10,2),
    finished BOOLEAN NOT NULL,
    match_url VARCHAR(200),
    home_possession INTEGER,
    away_possession INTEGER,
    home_expected_goals_xg DECIMAL(5,2),
    away_expected_goals_xg DECIMAL(5,2),
    home_total_shots INTEGER,
    away_total_shots INTEGER,
    home_shots_on_target INTEGER,
    away_shots_on_target INTEGER,
    home_big_chances INTEGER,
    away_big_chances INTEGER,
    home_big_chances_missed INTEGER,
    away_big_chances_missed INTEGER,
    home_accurate_passes INTEGER,
    away_accurate_passes INTEGER,
    home_accurate_passes_pct INTEGER,
    away_accurate_passes_pct INTEGER,
    home_fouls_committed INTEGER,
    away_fouls_committed INTEGER,
    home_corners INTEGER,
    away_corners INTEGER,
    home_xg_open_play DECIMAL(5,2),
    away_xg_open_play DECIMAL(5,2),
    home_xg_set_play DECIMAL(5,2),
    away_xg_set_play DECIMAL(5,2),
    home_non_penalty_xg DECIMAL(5,2),
    away_non_penalty_xg DECIMAL(5,2),
    home_xg_on_target_xgot DECIMAL(5,2),
    away_xg_on_target_xgot DECIMAL(5,2),
    home_shots_off_target INTEGER,
    away_shots_off_target INTEGER,
    home_blocked_shots INTEGER,
    away_blocked_shots INTEGER,
    home_hit_woodwork INTEGER,
    away_hit_woodwork INTEGER,
    home_shots_inside_box INTEGER,
    away_shots_inside_box INTEGER,
    home_shots_outside_box INTEGER,
    away_shots_outside_box INTEGER,
    home_passes INTEGER,
    away_passes INTEGER,
    home_own_half INTEGER,
    away_own_half INTEGER,
    home_opposition_half INTEGER,
    away_opposition_half INTEGER,
    home_accurate_long_balls INTEGER,
    away_accurate_long_balls INTEGER,
    home_accurate_long_balls_pct INTEGER,
    away_accurate_long_balls_pct INTEGER,
    home_accurate_crosses INTEGER,
    away_accurate_crosses INTEGER,
    home_accurate_crosses_pct INTEGER,
    away_accurate_crosses_pct INTEGER,
    home_throws INTEGER,
    away_throws INTEGER,
    home_touches_in_opposition_box INTEGER,
    away_touches_in_opposition_box INTEGER,
    home_offsides INTEGER,
    away_offsides INTEGER,
    home_yellow_cards INTEGER,
    away_yellow_cards INTEGER,
    home_red_cards INTEGER,
    away_red_cards INTEGER,
    home_tackles_won INTEGER,
    away_tackles_won INTEGER,
    home_tackles_won_pct INTEGER,
    away_tackles_won_pct INTEGER,
    home_interceptions INTEGER,
    away_interceptions INTEGER,
    home_blocks INTEGER,
    away_blocks INTEGER,
    home_clearances INTEGER,
    away_clearances INTEGER,
    home_keeper_saves INTEGER,
    away_keeper_saves INTEGER,
    home_duels_won INTEGER,
    away_duels_won INTEGER,
    home_ground_duels_won INTEGER,
    away_ground_duels_won INTEGER,
    home_ground_duels_won_pct INTEGER,
    away_ground_duels_won_pct INTEGER,
    home_aerial_duels_won INTEGER,
    away_aerial_duels_won INTEGER,
    home_aerial_duels_won_pct INTEGER,
    away_aerial_duels_won_pct INTEGER,
    home_successful_dribbles INTEGER,
    away_successful_dribbles INTEGER,
    home_successful_dribbles_pct INTEGER,
    away_successful_dribbles_pct INTEGER,
    fotmob_id BIGINT,
    stats_processed BOOLEAN DEFAULT FALSE,
    player_stats_processed BOOLEAN DEFAULT FALSE
);

-- Create indexes for common query patterns
CREATE INDEX idx_matches_gameweek ON matches(gameweek);
CREATE INDEX idx_matches_home_team ON matches(home_team);
CREATE INDEX idx_matches_away_team ON matches(away_team);
CREATE INDEX idx_matches_kickoff_time ON matches(kickoff_time);
CREATE INDEX idx_matches_finished ON matches(finished);
CREATE INDEX idx_matches_fotmob_id ON matches(fotmob_id);